### ISSUE TITLE
`get_track_comments` fails for tracks with comments from 2011 due to a missing timestamp field

### ISSUE THREAD

**Issue by idancohen88** [7x11x13/soundcloud.py#10]
It turns out that old comments, at least from 2011, may be without the `timestamp` field. Therefore, the `get_track_comments` function fails and raises `WrongTypeError`:
```
/.venv/lib/python3.11/site-packages/dacite/core.py", line 69, in from_dict
    raise WrongTypeError(field_path=field.name, field_type=field_type, value=value)
dacite.exceptions.WrongTypeError: wrong value type for field "timestamp" - should be "int" instead of value "None" of type "NoneType"
```

Steps to reproduce:
```
url="https://soundcloud.com/realblackcoffee/2nd-may-mix"
client = SoundCloud()
track = client.resolve(url)
track_id = track.id
all_comments = list(client.get_track_comments(
    track_id, threaded=1, sort="track-created_at"
))
```

**Comment by 7x11x13** [comment]
Fixed in v1.5.4, thanks for the report. BTW, for queries like that it will be faster if you supply the kwarg "limit", e.g. `client.get_track_comments(track_id, threaded=1, sort="track-created_at", limit=1000)` as the default limit is something really small... I should document this somewhere
