### ISSUE TITLE
Provide a LICENSE file

### ISSUE THREAD

**Issue by phijor** [7x11x13/soundcloud.py#2]
I'm packaging you library for the [Arch User Repository](https://aur.archlinux.org/packages/python-soundcloud-v2), and I noticed that it does not provide a separate LICENSE file.  If I understand correctly, this project is licensed under the terms of the MIT license, which technically has project specific wording.

Would you mind adding that to the repository, with the information on the following line of the license filled in:

```
Copyright (c) [year] [fullname]
```

That way, I can properly package your project, making it available for people to install on Arch Linux.

**Comment by 7x11x13** [comment]
Added LICENSE file
