### ISSUE TITLE
BaseTrack.has_downloads_left not returning correct value

### ISSUE THREAD

**Issue by hunkyburrito** [7x11x13/soundcloud.py#4]
Was looking into #https://github.com/flyingrub/scdl/issues/431 when I found that `BaseTrack.has_downloads_left` always returned `False` if you were downloading from favorites. I checked the public api page and could not find any mention of a download limit but I don't know if v2 has anything.

**Comment by 7x11x13** [comment]
The download limits are 100 per track for free users, or 1000 per track for pro users, according to [this page.](https://help.soundcloud.com/hc/en-us/articles/115003565708-Enabling-downloads-for-your-track)

If BaseTrack.has_downloads_left is always returning false, then it's probably deprecated, and maybe it would be enough to check BaseTrack.downloadable. Or maybe you would have to check download_count and whether the uploader is pro or not.

**Comment by hunkyburrito** [comment]
It seems like it works for normal tracks but when it's a track from likes it doesn't. Either way I might just remove that check like you suggested.
